apiVersion: apps/v1
kind: Deployment
metadata:
  name: peercode-react
  labels:
    app: peercode-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peercode-react
  template:
    metadata:
      labels:
        app: peercode-react
    spec:
      containers:
        - name: peercode-react
          image: ${ECR}:${SHA}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: config
                key: NODE_ENV
          - name: REACT_APP_MATCHMAKING_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: config
                key: REACT_APP_MATCHMAKING_TIMEOUT
          - name: REACT_APP_API_GATEWAY
            valueFrom:
              configMapKeyRef:
                name: config
                key: REACT_APP_API_GATEWAY
          - name: REACT_APP_SOCKET_URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: REACT_APP_SOCKET_URL
          - name: REACT_APP_FIREBASE_API_KEY
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_API_KEY
          - name: REACT_APP_FIREBASE_AUTH_DOMAIN
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_AUTH_DOMAIN
          - name: REACT_APP_FIREBASE_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_PROJECT_ID
          - name: REACT_APP_FIREBASE_STORAGE_BUCKET
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_STORAGE_BUCKET
          - name: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
          - name: REACT_APP_FIREBASE_APP_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_APP_ID
          - name: REACT_APP_FIREBASE_MEASUREMENT_ID
            valueFrom:
              secretKeyRef:
                name: secret
                key: REACT_APP_FIREBASE_MEASUREMENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: peercode-react
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-tls-cert: arn:aws:acm:ap-southeast-1:585416986583:certificate/ae5381a8-a0a2-4e1b-987e-d7aa63a52596
    # Only run TLS on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-tls-ports: "https"
spec:
  type: LoadBalancer
  selector:
    app: peercode-react
  ports:
    - name: http 
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
