name: Build and Deploy React App

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm i

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements-dev.txt

      - name: Build app
        run: docker-compose -f docker-compose.yml build

      - name: Run app
        run: bash start.sh

      - name: Run system tests
        run: |
          cd system_test
          pytest
