name: Build and Deploy React App

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 

      - name: Change directory to frontend
        run: cd frontend

      - name: Install dependencies
        run: npm i

      - name: Change directory to backend
        run: cd backend

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements-dev.txt

      - name: Change directory to root
        run: cd ..

      - name: Build app
        run: docker-compose -f docker-compose.yml build

      - name: Run app
        run: bash start.sh

      - name: Change directory to system_test
        run: cd system_test

      - name: Run tests
        run: pytest
