name: System test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: System test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Google Chrome 
      run: |
        chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        cd system_test
        pytest